import type { NextPage } from 'next';
import Head from 'next/head';

import { ToastContainer } from 'react-toastify';
import { StoreProvider } from '/src/store/StoreProvider';

import { App } from '/src';
import styles from '../styles/Home.module.css';
import 'react-toastify/dist/ReactToastify.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>To-Do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <StoreProvider>
        <App />
      </StoreProvider>

      <ToastContainer />
    </div>
  );
};

export default Home;
